version: '3.8'

services:
  caddy:
    build: .
    container_name: kupkid-site
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/caddy:Z
    restart: unless-stopped
    depends_on:
      - api
  
  api:
    image: python:3.11-alpine
    container_name: kupkid-api
    working_dir: /app
    volumes:
      - .:/app:Z
    command: >
      sh -c "python3 server.py"
    restart: unless-stopped
    ports:
      - "8081:8081"
